language: cpp
os:
  - linux
compiler:
  - g++
install:
  - sudo pip install codecov
script:
  - make
  - make test
  - make gcov
branches:
  only:
    - master
after_success:
  - codecov -t 914c93ef-c8af-4c6d-a748-a8f8d8bddab7 -X gcov
